export const FGames = [
  {
    image: "/homepage/CoverScreenGame1.png",
    name: "Assassin's Creed Valhalla",
    genre: "Action RPG",
    price: 2599,
    rating: 4.6,
    sold: 3000,
    description: [
      "Explore Viking-era England",
      "Engaging combat and stealth",
      "Beautiful open-world landscapes",
    ],
  },
  {
    image: "/homepage/CoverScreenGame3.jpg",
    name: "Tekken 8",
    genre: "Fighting",
    price: 2999,
    rating: 4.7,
    sold: 1500,
    description: [
      "Advanced combat mechanics",
      "Diverse roster of characters",
      "Next-gen visuals and effects",
    ],
  },
  {
    image: "/homepage/CoverScreenGame4.png",
    name: "Cyberpunk 2077",
    genre: "Action RPG",
    price: 2999,
    rating: 4.5,
    sold: 1000,
    description: [
      "Immersive storyline",
      "Futuristic open-world",
      "Amazing graphics",
    ],
  },
  {
    image: "/homepage/CoverScreenGame5.png",
    name: "Hitman",
    genre: "Stealth Action",
    price: 2499,
    rating: 4.8,
    sold: 2000,
    description: [
      "Master assassin gameplay",
      "Dynamic mission environments",
      "Stealth and strategy focused",
    ],
  },
  {
    image: "/homepage/CoverScreenGame1.png",
    name: "Assassin's Creed Valhalla",
    genre: "Action RPG",
    price: 2599,
    rating: 4.6,
    sold: 3000,
    description: [
      "Explore Viking-era England",
      "Engaging combat and stealth",
      "Beautiful open-world landscapes",
    ],
  },
  {
    image: "/homepage/CoverScreenGame3.jpg",
    name: "Tekken 8",
    genre: "Fighting",
    price: 2999,
    rating: 4.7,
    sold: 1500,
    description: [
      "Advanced combat mechanics",
      "Diverse roster of characters",
      "Next-gen visuals and effects",
    ],
  },
  {
    image: "/homepage/CoverScreenGame4.png",
    name: "Cyberpunk 2077",
    genre: "Action RPG",
    price: 2999,
    rating: 4.5,
    sold: 1000,
    description: [
      "Immersive storyline",
      "Futuristic open-world",
      "Amazing graphics",
    ],
  },
  {
    image: "/homepage/CoverScreenGame5.png",
    name: "Hitman",
    genre: "Stealth Action",
    price: 2499,
    rating: 4.8,
    sold: 2000,
    description: [
      "Master assassin gameplay",
      "Dynamic mission environments",
      "Stealth and strategy focused",
    ],
  },
];
